# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/zeroqaret',
                'doc_host': 'https://bengsoon.github.io',
                'git_url': 'https://github.com/bengsoon/zeroqaret',
                'lib_path': 'zeroqaret'},
  'syms': {'zeroqaret.core': {'zeroqaret.core.foo': ('core.html#foo', 'zeroqaret/core.py')}}}
